✨ | Improvements
NamVr/DiscordBot-Template pull request #27
Opened 2023-04-10 19:13 UTC by TecEash1

- Added a cooldown config for slash commands

- Buttons can now have multiple folders/subfolders

2023-04-10 19:14 UTC, TecEash1 commented
I am not sure if this still allows for typescript assistant support... but I thought I would make a pr to help out. 
sorry if it doesn't 😅

2023-04-10 19:30 UTC, StormPacer commented on bot.js
> +	ActivityType,
ActivityType is not used in the code, it should be removed.

2023-04-10 19:31 UTC, StormPacer commented on bot.js
> +		GatewayIntentBits.DirectMessages,
Not sure why this was switched around, not that it matters but still a weird change.

2023-04-10 19:33 UTC, StormPacer commented on bot.js
> +		client.on(event.name, async (...args) => await event.execute(...args, client));
Nothing was changed about the events part of the code, you should follow the repository's formatting using prettier.

2023-04-10 19:34 UTC, StormPacer commented on bot.js
> +}
This seems redundant, I see no use for folders within folders in the button handler.

2023-04-10 19:42 UTC, StormPacer requested changes
The cooldown code works, the @version number in `slashCreate.js` needs to be changed to the new version number of the bot (I recommend the new version to be 3.4.0). You also need to add an example to the `help.js` slash command so people know how you can use cooldowns.

However, there are a lot of random commits that don't quite fit with the template or are not good to have in the template. I recommend looking over my comments and fixing accordingly.

2023-04-10 21:38 UTC, TecEash1 commented on bot.js
> +}
👍, I just use it quite a bit as I have quite a lot of buttons. 
- I’ll remove that tho.

2023-04-11 04:26 UTC, NamVr commented on bot.js
> +		GatewayIntentBits.DirectMessages,
I don't understand the change, was DM intents not a part of code earlier so it is added now?
Also are we using DM commands by the way so it needs to be edited?

2023-04-11 04:28 UTC, NamVr commented on bot.js
> +		client.on(event.name, async (...args) => await event.execute(...args, client));
Why are you adding author tags everywhere editing nothing 🤔

2023-04-11 04:34 UTC, NamVr commented
I've personally checked the commits and I think bot.js has gone with no valid changes and it should be returned to the default state before the PR (with no changes),
For slash.js command cooldown can be a good feature, however the code needs to be optimised to reduce bloat.
Lastly please use prettier as default formatter.

2023-04-11 09:41 UTC, TecEash1 commented
> I've personally checked the commits and I think bot.js has gone with no valid changes and it should be returned to the default state before the PR (with no changes), For slash.js command cooldown can be a good feature, however the code needs to be optimised to reduce bloat. Lastly please use prettier as default formatter.

👍Ill remove everything else and make the cooldown better, like the other one in the prefix commands

2023-04-11 09:43 UTC, TecEash1 commented on bot.js
> +		GatewayIntentBits.DirectMessages,
o sorry about that, I was using it for something else and removed it and added it back... ill fix it

2023-04-11 12:02 UTC, NamVr requested changes
Please use prettier properly, like said below by @StormPacer

2023-04-11 12:03 UTC, NamVr commented on events/slashCreate.js
> +    const defaultCooldownDuration = 0;
Why do we need this, zero can directly be written in next line?

2023-04-11 12:05 UTC, NamVr commented
Why did you force pushed branch? It wasnt' necessary?

2023-04-11 13:01 UTC, TecEash1 commented
> Why did you force pushed branch? It wasnt' necessary?

to keep it all in 1 commit

2023-04-11 13:10 UTC, TecEash1 commented
> Please use prettier properly, like said below by @StormPacer

I put it all into prettier and that's how it formatted it...

2023-04-11 13:39 UTC, NamVr commented
It wasn't necessary since I always squash and merge.
I'm pretty sure it's the wrong formatting for prettier since all files are changed.
Do you mind if I close the PR and update this new command myself?

2023-04-11 13:51 UTC, TecEash1 commented
> It wasn't necessary since I always squash and merge.
> I'm pretty sure it's the wrong formatting for prettier since all files are changed.
> Do you mind if I close the PR and update this new command myself?

O ok, I used the prettier website and it seemed to format it like that for me. 
I think u have perms to make commits to the fork to update it tho

2023-04-11 17:42 UTC, TecEash1 commented
> Prettier website? I don't know what you're talking about, but there exists a Prettier extension on VS Code which is officially supported by us.
> Go to VS Code settings after installation of the above extension and then make it as default formatter for your code, make sure your code auto formats after every save.
> Then format your files by saving them it should solved all issues.

k ill try that, it said on [their website](https://prettier.io/) that it was the same, sorry about that

2023-04-11 18:10 UTC, TecEash1 commented
<img width="443" alt="image" src="https://user-images.githubusercontent.com/92249532/231252176-0217824f-699d-442a-becb-5b6a505b8137.png">
<img width="514" alt="image" src="https://user-images.githubusercontent.com/92249532/231252263-6222b5ac-39f4-43e3-bab9-ea3c67053381.png">
<img width="589" alt="image" src="https://user-images.githubusercontent.com/92249532/231252308-57e262c3-25b5-4031-bb97-5a8470b80823.png">

2023-04-11 18:30 UTC, NamVr commented
I think most of it is now prettified and fix, does the cooldown property support Intellisense autocompletion? 
You might have to add property in typings.d.ts of "cooldown" in slash commands.

Otherwise, requesting review from @StormPacer !

2023-04-14 19:15 UTC, NamVr commented
Hi, you were requested to complete the PR few days ago, please do it soon or we will have to close it.
(Can't review unless the full feature is completed)

2023-04-14 21:19 UTC, TecEash1 commented
> Hi, you were requested to complete the PR few days ago, please do it soon or we will have to close it.
> (Can't review unless the full feature is completed)

O ok, I thought storm was gonna do it that was y, mb 😅. I’ll try figure out how to add it tmr. Havnt rly looked into ts

2023-04-15 10:22 UTC, TecEash1 commented
<img width="224" alt="image" src="https://user-images.githubusercontent.com/92249532/232208184-7d8de309-420d-44cb-a9ef-d12e4f7d82b1.png">
Would that be how you would add it...?

2023-04-15 10:35 UTC, NamVr commented
Yes it was really that simple.
Just check the cooldown property in legacy command on how it is written.

2023-04-15 10:37 UTC, closed without merging

2023-04-15 11:05 UTC, TecEash1 commented
would you like me to change anything else?

2023-04-15 11:45 UTC, NamVr commented
No, you're really trying to waste our times here I believe hence I have closed this request. This is a PR not a guide or a tutorial, you're expected to open a PR if you want to contribute, if we have to help you to be able to you to contribute the PR makes no sense and I can create the feature myself too.

2023-04-15 11:56 UTC, TecEash1 commented
k, I'm sorry for waisting your time